language: ruby

rvm:
  - 2.3.0

bundler_args: --without development --deployment

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - npm install

script:
  - bundle exec rspec spec
