default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: root
  timeout: 5000

development:
  <<: *default
  database: vote_app_dev

test:
  <<: *default
  database: vote_app_test

production:
  <<: *default
  database: vote_app
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
