default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>

default_facebook: &default_facebook
  facebook_api_key: <%= ENV["FACEBOOK_API_KEY"] %>
  facebook_api_secret: <%= ENV["FACEBOOK_API_SECRET"] %>

development:
  secret_key_base: e7401998983033a0d1d36c3d14219128cd7686dd89198727e518125952bd92837adb48c42725ca5d008913a67bac1af220f9cbb3fd64f476868104510cb24a66
  <<: *default_twitter
  <<: *default_facebook

test:
  secret_key_base: e85e51ee3f588bc57823e21c130de51aa38d5333ae1a9f84509675ba7ddbe25a316a6abd7445d2f826fe1223f5dfb2b79722b76e16a9ce054494f7d71511531c
  <<: *default_twitter
  <<: *default_facebook

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *default_twitter
  <<: *default_facebook
